/************************************************************************
* Version   Date        Name        Description
*========================================================================
* v1.0      2025-07-18  Developer1  Add method implemented
*
*************************************************************************/
public with sharing class Calculator {
    public Calculator() {

    }
    public Integer sub(integer a, Integer b) {
        return a-b;
    }
    public Integer add(integer a, integer b) {
        return a+b;
    }

}
